// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHFnY2PyiNwvmN_4EVTr83NQ802-Nr6-c',
    appId: '1:329599814176:web:bf6d7c69b604e17d994a45',
    messagingSenderId: '329599814176',
    projectId: 'expense-tracker-cc8ed',
    authDomain: 'expense-tracker-cc8ed.firebaseapp.com',
    storageBucket: 'expense-tracker-cc8ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVp3BaFgF-lhwfBO-WU8sWHyJmCocOMF0',
    appId: '1:329599814176:android:e73e41db4e28cc32994a45',
    messagingSenderId: '329599814176',
    projectId: 'expense-tracker-cc8ed',
    storageBucket: 'expense-tracker-cc8ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHENKBes3kDRHl1L0QpWRMl-K8bj8flvY',
    appId: '1:329599814176:ios:28ab4d6970a2ad02994a45',
    messagingSenderId: '329599814176',
    projectId: 'expense-tracker-cc8ed',
    storageBucket: 'expense-tracker-cc8ed.firebasestorage.app',
    iosBundleId: 'com.truecube.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHENKBes3kDRHl1L0QpWRMl-K8bj8flvY',
    appId: '1:329599814176:ios:28ab4d6970a2ad02994a45',
    messagingSenderId: '329599814176',
    projectId: 'expense-tracker-cc8ed',
    storageBucket: 'expense-tracker-cc8ed.firebasestorage.app',
    iosBundleId: 'com.truecube.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHFnY2PyiNwvmN_4EVTr83NQ802-Nr6-c',
    appId: '1:329599814176:web:e999e22dbb1c58f8994a45',
    messagingSenderId: '329599814176',
    projectId: 'expense-tracker-cc8ed',
    authDomain: 'expense-tracker-cc8ed.firebaseapp.com',
    storageBucket: 'expense-tracker-cc8ed.firebasestorage.app',
  );

}